### ISSUE TITLE
[TDBottomTabBar] 在bottomNavigationBar中使用时，直接赋值，会撑满整个屏幕，并且也没做安全区域的限制

### ISSUE THREAD

**Issue by BingKui** [Tencent/tdesign-flutter#1]
### tdesign-flutter 版本

0.1.0

### 重现步骤

import 'package:flutter/material.dart';
import 'package:tdesign_flutter/tdesign_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: false,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const TDNavBar(
        title: "TDesign Demo",
        rightBarItems: [],
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      bottomNavigationBar: TDBottomTabBar(
        TDBottomTabBarBasicType.iconText,
        componentType: TDBottomTabBarComponentType.label,
        outlineType: TDBottomTabBarOutlineType.capsule,
        useVerticalDivider: false,
        barHeight: 56,
        navigationTabs: [
          TDBottomTabBarTabConfig(
            iconTextTypeConfig: IconTextTypeConfig(useDefaultIcon: true, tabText: '标签'),
            tabText: '标签',
            onTap: () {
              // onTapTab(context, '标签1');
            },
          ),
          TDBottomTabBarTabConfig(
            iconTextTypeConfig: IconTextTypeConfig(useDefaultIcon: true, tabText: '标签'),
            tabText: '标签',
            onTap: () {
              // onTapTab(context, '标签2');
            },
          ),
          TDBottomTabBarTabConfig(
            iconTextTypeConfig: IconTextTypeConfig(useDefaultIcon: true, tabText: '标签'),
            tabText: '标签',
            onTap: () {
              // onTapTab(context, '标签3');
            },
          ),
        ],
      ),
      floatingActionButton: TDButton(
        icon: TDIcons.add,
        onTap: _incrementCounter,
        shape: TDButtonShape.circle,
        type: TDButtonType.fill,
        size: TDButtonSize.large,
        theme: TDButtonTheme.primary,
      ),
    );
  }
}

### 期望结果

期望按照实际高度显示，并且做底部安全区域的处理

### 实际结果

撑满整个页面，底部也没做安全区域的处理
![image](https://github.com/Tencent/tdesign-flutter/assets/6781005/a8c5d3c4-8cb9-4359-abc7-52e57b33838d)

### 设备与机型信息

iOS 15 pro

### 系统版本

iOS17

**Comment by iounce** [comment]
有一种方式将控件TDBottomTabBar放置到body之中，然后使用Spacer()控件调整位置
![image](https://github.com/Tencent/tdesign-flutter/assets/86102858/eaada303-b1d2-4697-9e64-31534b0cd94b)

**Comment by Luozf12345** [comment]
0.1.2版本已修复
