### ISSUE TITLE
[TDLoading] loading不支持快速关闭

### ISSUE THREAD

**Issue by littleantfly** [Tencent/tdesign-flutter#10]
### 这个功能解决了什么问题

当我在页面上显示出loading组件后，我需要在数据加载完成后主动的关闭loading组件。

### 你建议的方案是什么

希望可以有API方便的主动关闭loading的组件，类似：TDToast.dismissLoading;

**Comment by Luozf12345** [comment]
感谢反馈，已收到，这边评估一下排期，会尽快迭代发版

**Comment by Luozf12345** [comment]
0.1.2版本已支持
