### ISSUE TITLE
[Toast] Toast不支持遮罩

### ISSUE THREAD

**Issue by wulianpu** [Tencent/tdesign-flutter#103]
Toast目前不支持遮罩，是有什么其他的考虑吗

## IssueShoot
- 预估时长：2
- 期望完成时间：2025-1-24
- 开发难度：中
- 参与人数：1
- 需求对接人：zflyluo
- 验收标准：实现期望改造效果，提 MR并通过 验收无误
- 备注：最终激励以实际提交 pr 并合并为准

**Comment by Luozf12345** [comment]
请问“遮罩”具体是哪种样式呢？可以加如反馈群详细沟通下吗？

**Comment by wulianpu** [comment]
就是像tdesign-vue里面一样的，https://tdesign.tencent.com/mobile-vue/components/toast
<img width="373" alt="image" src="https://github.com/Tencent/tdesign-flutter/assets/44516614/cc16425f-fd31-4dd0-bc61-19159a9a4306">

**Comment by wulianpu** [comment]
> 请问“遮罩”具体是哪种样式呢？可以加如反馈群详细沟通下吗？

反馈群怎么加呀

**Comment by wulianpu** [comment]
> > 请问“遮罩”具体是哪种样式呢？可以加如反馈群详细沟通下吗？
> 
> 反馈群怎么加呀

我在首页找到了
