### ISSUE TITLE
[TDTabBar]   labelStyle 不起作用

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#108]
### tdesign-flutter 版本

0.1.4

### 实际结果

labelStyle 不起作用，unselectedLabelStyle， 这个样式也不起作用

**Comment by wiscgazf** [comment]
我的也不生效 哈哈
`import 'package:extended_nested_scroll_view/extended_nested_scroll_view.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:tdesign_flutter/tdesign_flutter.dart';
import 'package:xjy_study/utils/color_util.dart';

class StudyDetail extends StatefulWidget {
  const StudyDetail({super.key});

  @override
  State<StatefulWidget> createState() => _StudyDetailState();
}

class _StudyDetailState extends State<StudyDetail> with SingleTickerProviderStateMixin {
  final List<String> _tabs = const ['待上课时', '已上课时'];

  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: _tabs.length, vsync: this);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _getQueryParams();
  }

  @override
  void dispose() {
    super.dispose();
  }

  void _getQueryParams() {
    final ModalRoute<Object?>? currentRoute = ModalRoute.of(context);
    if (currentRoute != null) {
      final Map<String, dynamic> params = currentRoute.settings.arguments as Map<String, dynamic>;
      print('aa=${params}');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('课程详情'),
        leadingWidth: 40.w,
      ),
      body: ExtendedNestedScrollView(
        onlyOneScrollInBody: true,
        physics: ClampingScrollPhysics(),
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [
            SliverToBoxAdapter(
              child: _CourseItemDetail(),
            )
          ];
        },
        body: Column(
          children: [
            TDTabBar(
                controller: _tabController,
                height: 44.h,
                backgroundColor: Colors.white,
                indicatorColor: ColorUtil.primaryColor(),
                labelColor: ColorUtil.primaryColor(),
                unselectedLabelStyle: TextStyle(fontSize: 12.sp, color: Colors.red),
                labelStyle: TextStyle(
                    fontSize: 18.sp,
                    color: ColorUtil.primaryFontColor(),
                    fontWeight: FontWeight.w500),
                indicatorWidth: 16.w,
                showIndicator: true,
                tabs: _tabs
                    .map((e) => TDTab(
                          text: '$e',
                        ))
                    .toList()),
            Expanded(
                child: TDTabBarView(
                    isSlideSwitch: true,
                    controller: _tabController,
                    children: _tabs
                        .map((e) => Center(
                              child: Text('data$e'),
                            ))
                        .toList()))
          ],
        ),
      ),
    );
  }
}

/// 课程详情描述
class _CourseItemDetail extends StatelessWidget {
  const _CourseItemDetail();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.fromLTRB(15.w, 10.h, 15.w, 8.h),
      color: Colors.white,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                margin: EdgeInsets.only(top: 3.h),
                height: 16.h,
                alignment: Alignment.center,
                padding: EdgeInsets.symmetric(horizontal: 6.w),
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.all(Radius.circular(4)),
                    gradient: LinearGradient(colors: [
                      ColorUtil.hexColorString('#FFB442'),
                      ColorUtil.hexColorString('#FF9A00')
                    ])),
                child: Text(
                  '数学',
                  style: TextStyle(color: Colors.white, fontSize: 12.sp, height: 1.h),
                ),
              ),
              SizedBox(
                width: 8.w,
              ),
              Expanded(
                  child: Text(
                '集合图形离开撒娇的案例三等奖集合图形离开撒娇的案例',
                style: TextStyle(
                    color: ColorUtil.primaryFontColor(),
                    fontSize: 14.sp,
                    overflow: TextOverflow.ellipsis,
                    height: 1.5.h),
                maxLines: 2,
              ))
            ],
          ),
          Padding(
            padding: EdgeInsets.only(top: 5.h, bottom: 12.h),
            child: Text(
              '2020年8月15日开始，共20节课',
              style: TextStyle(fontSize: 12.sp, color: ColorUtil.subFontColor()),
            ),
          ),
          Row(
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(28.w),
                child: Container(
                  width: 28.w,
                  height: 28.w,
                  color: Colors.grey,
                ),
              ),
              SizedBox(
                width: 10.w,
              ),
              Text(
                '某某老师',
                maxLines: 1,
                style: TextStyle(
                    fontSize: 12.sp,
                    color: ColorUtil.subFontColor(),
                    overflow: TextOverflow.ellipsis),
              )
            ],
          )
        ],
      ),
    );
  }
}
`

**Comment by Luozf12345** [comment]
关联issue:https://github.com/Tencent/tdesign-flutter/issues/188
