### ISSUE TITLE
[TDBottomTabBar] 发现这个组件没有类似像 currentIndex 之类的参数

### ISSUE THREAD

**Issue by Epilogue-P** [Tencent/tdesign-flutter#110]
### 这个功能解决了什么问题

我想用 TabBar 做为底部导航栏进行路由导航，理论上我点击 TabBar 会根据 onTap 去跳转路由，TabBar 组件内部在 _onTap 方法内改变了高亮/聚焦属性 _selectedIndex ，但是我发现如果我的路由不仅仅会根据点击 TabBar 去改变，我无法根据新路由去匹配激活 TabBar 某一项的高亮/聚焦。我查看了 API 文档以及源码（顺带翻看了一下issue），没有找到类似的功能或反馈（可能是我看漏掉了？╮(╯▽╰)╭）。

### 你建议的方案是什么

希望参考 BottomNavigationBar 组件提供类似 currentIndex 的参数，或者有其他能解决需求的方法(*^▽^*)，感谢。

**Comment by 1213540239** [comment]
刚发现我的需求和这个有点接近 https://github.com/Tencent/tdesign-flutter/issues/80

**Comment by Epilogue-P** [comment]
d

**Comment by Luozf12345** [comment]
0.1.5版本已支持
