### ISSUE TITLE
[TDInput] 希望加入类似 TextField 的 onTapOutside 事件，用于点击空白区域键盘回收

### ISSUE THREAD

**Issue by Epilogue-P** [Tencent/tdesign-flutter#116]
### 这个功能解决了什么问题

能解决输入框聚焦后，点击其他空白区域的键盘回收，我尝试过

### 你建议的方案是什么

希望加入类似 TextField 的 onTapOutside 事件，自己实现太不优雅了o(╥﹏╥)o

**Comment by Luozf12345** [comment]
感谢反馈，我们评估一下这个能力怎么实现比较好

**Comment by Luozf12345** [comment]
https://github.com/Tencent/tdesign-flutter/pull/280
这个pr已实现
