### ISSUE TITLE
[TDInput] 清除按钮能与getx结合吗？

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#124]
### 这个功能解决了什么问题

oncleartap加了，后面的那个x清除的没有出现。
![wecom-temp-337764-d1d6f87ce07b8745377fcbc47695bfef](https://github.com/Tencent/tdesign-flutter/assets/35024333/f0b3b429-abf5-43d9-a19a-bec52d02ea19)

在onChange之后调setState更新一下页面，不好与getx结合使用

### 你建议的方案是什么

需要能与getx结合

**Comment by 985211yyg** [comment]
GetBuilder<LoginPageController>(
                    id: 'account',
                    init: controller,
                    builder: (innerController) {
                      return TDInput(
                        controller: controller.accountController,
                        textStyle: TextStyles.blackBold16,
                        hintTextStyle: TextStyles.black16
                            .copyWith(color: ColorCenter.forthTextColor),
                        leftIcon: Icon(
                          Icons.person,
                          color: ColorCenter.primaryColor,
                        ),
                        backgroundColor: Colors.white,
                        hintText: '请输入账号',
                        maxLines: 1,
                        onChanged: (text) {
                          innerController.update(["account"]);
                        },
                        onClearTap: () {
                          innerController.accountController.clear();
                          innerController.update(["account"]);
                        },
                      );
                    },
                  ) 

TDInput是无状态的，在getX中  用 GetBuilder包裹局部刷新 @Luozf12345

**Comment by Luozf12345** [comment]
清除按钮已优化
