### ISSUE TITLE
[TDInput] 焦点丢失

### ISSUE THREAD

**Issue by Coral-Y** [Tencent/tdesign-flutter#129]
### tdesign-flutter 版本

0.1.4

### 重现步骤

登录页面
1.点击账号输入框弹起键盘
2.不收起键盘直接点击密码输入框
3.弹出安全键盘，但是密码输入框失去焦点

### 期望结果

点击密码输入框后弹出安全键盘，且输入框不失去焦点 

### Flutter版本

3.19.1

### 设备与机型信息

HUAWEI Mate 30

### 系统版本

HarmonyOS 4

**Comment by Luozf12345** [comment]
感谢反馈，我们确认一下，尽快修复~

**Comment by cookie-y** [comment]
我直接使用TextField组件也会存在同样的问题，在Flutter的github issue中，找到了同样的问题，目前还是Open的状态
[144658](https://github.com/flutter/flutter/issues/144658)
华为和荣耀的机型会存在这个问题

**Comment by hiFrankYoung** [comment]
呐

```dart
Listener(
          onPointerDown: (e) => {
            FocusScope.of(context).unfocus(),
          },
          child: TDInput(
            type: TDInputType.cardStyle,
            width: context.widthPx - 20,
            leftIcon: const Icon(TDIcons.mail),
            leftLabel: 'Email',
            backgroundColor: Colors.white,
            hintText: 'Please input email',
            onChanged: (email) {
              debug(email);
              controller.email.value = email;
            },
          ),
        )
```

**Comment by qycqlq** [comment]
> 我直接使用TextField组件也会存在同样的问题，在Flutter的github issue中，找到了同样的问题，目前还是Open的状态 [144658](https://github.com/flutter/flutter/issues/144658) 华为和荣耀的机型会存在这个问题

，我也碰到了类似的问题，刚好，我手上有个华为和荣耀的手机，华为的没有问题，荣耀的有，发现不仅仅失去焦点，有时候还有键盘的类型无法修改的问题，这个问题有解决方案？

**Comment by hiFrankYoung** [comment]
> > 我直接使用TextField组件也会存在同样的问题，在Flutter的github issue中，找到了同样的问题，目前还是Open的状态 [144658](https://github.com/flutter/flutter/issues/144658) 华为和荣耀的机型会存在这个问题
> 
> 
> 
> ，我也碰到了类似的问题，刚好，我手上有个华为和荣耀的手机，华为的没有问题，荣耀的有，发现不仅仅失去焦点，有时候还有键盘的类型无法修改的问题，这个问题有解决方案？

我上方回复的那段demo不可以解决这个丢失焦点的问题吗？
我这边测试是可以的。

**Comment by qycqlq** [comment]
> > > 我直接使用TextField组件也会存在同样的问题，在Flutter的github issue中，找到了同样的问题，目前还是Open的状态 [144658](https://github.com/flutter/flutter/issues/144658) 华为和荣耀的机型会存在这个问题
> > 
> > 
> > ，我也碰到了类似的问题，刚好，我手上有个华为和荣耀的手机，华为的没有问题，荣耀的有，发现不仅仅失去焦点，有时候还有键盘的类型无法修改的问题，这个问题有解决方案？
> 
> 我上方回复的那段demo不可以解决这个丢失焦点的问题吗？ 我这边测试是可以的。

我试试

**Comment by qycqlq** [comment]
> > > 我直接使用TextField组件也会存在同样的问题，在Flutter的github issue中，找到了同样的问题，目前还是Open的状态 [144658](https://github.com/flutter/flutter/issues/144658) 华为和荣耀的机型会存在这个问题
> > 
> > 
> > ，我也碰到了类似的问题，刚好，我手上有个华为和荣耀的手机，华为的没有问题，荣耀的有，发现不仅仅失去焦点，有时候还有键盘的类型无法修改的问题，这个问题有解决方案？
> 
> 我上方回复的那段demo不可以解决这个丢失焦点的问题吗？ 我这边测试是可以的。

确实可以用，不过替换TextField，不知道会不会有其他问题，这个也是老东家的组件0.0，谢了
