### ISSUE TITLE
[TDImage] 只能通过network和asset获取图片

### ISSUE THREAD

**Issue by chuanyue98** [Tencent/tdesign-flutter#133]
### 这个功能解决了什么问题

只能通过network和asset获取图片吗吗，没有类似Image.FIle来获取的方式吗

### 你建议的方案是什么

希望可以增加Image.FIle来获取的方式，或者有其他办法吗，用户上传的图片放在asset好像不太方便？

**Comment by Luozf12345** [comment]
感谢反馈，我们确认下，后续版本添加

**Comment by Luozf12345** [comment]
0.1.5版本已支持
