### ISSUE TITLE
[TDBottomTabBar] 请求添加背景色 & barHeight高度问题

### ISSUE THREAD

**Issue by hiFrankYoung** [Tencent/tdesign-flutter#138]
### 这个功能解决了什么问题

1. 目前TDBottomTabBar 无法设置整个TabBar的背景色
2. TDBottomTabBar设置barHeight高度以后，如果basicType使用了iconText类型，会在icon和text之间有一段空白高度，无法修改

### 你建议的方案是什么

添加TDBottomTabBar的相关API

**Comment by Luozf12345** [comment]
感谢反馈，我们讨论一下，后面尽快支持上~

**Comment by Luozf12345** [comment]
0.1.5已修改
