### ISSUE TITLE
[Slider] TDesign 官网教程 Typo 错误

### ISSUE THREAD

**Issue by lz00qs** [Tencent/tdesign-flutter#145]
### tdesign-flutter 版本

0.1.4

### 重现链接

https://tdesign.tencent.com/flutter/components/slider

### 重现步骤

官网 Slider 的官方示例中 `>` 都被转译成了 `&gt;` ，如：`scaleFormatter: (value) =&gt; value.toInt().toString(),`
![Snipaste_2024-05-23_10-05-28](https://github.com/Tencent/tdesign-flutter/assets/42072641/ba579b0b-af3a-4145-92c7-5ceb7376f673)

### 期望结果

`>` 正常显示为 `>`

### Flutter版本

N/A

### 设备与机型信息

N/A

### 系统版本

N/A

**Comment by Luozf12345** [comment]
感谢反馈，应该是文档转化工具出了问题，我们看下吧
