### ISSUE TITLE
TDAvatar

### ISSUE THREAD

**Issue by thousandsNight** [Tencent/tdesign-flutter#16]
### 这个功能解决了什么问题

![image](https://github.com/Tencent/tdesign-flutter/assets/11659929/11df9a7d-a4f8-4ef4-8d86-3a982a99bcf0)

### 你建议的方案是什么

type设置为customText时可以变更背景色

**Comment by Luozf12345** [comment]
已收到，我们会在下个版本尽快发版解决

**Comment by Luozf12345** [comment]
0.1.2版本已支持
