### ISSUE TITLE
[TDNoticeBar] 公告栏（可滚动）

### ISSUE THREAD

**Issue by ccXxx1aoBai** [Tencent/tdesign-flutter#163]
### 这个功能解决了什么问题

通知组件--公告栏，支持滚动和步进

![Screenshot_20240530_170313](https://github.com/Tencent/tdesign-flutter/assets/97790229/17674143-ff17-45d9-a8cb-99a9cc62c398)

### 你建议的方案是什么

通知组件--公告栏，支持滚动和步进

**Comment by Luozf12345** [comment]
你好，感谢你的支持，新增组件可以加入反馈群，找群主详聊哈~

**Comment by ccXxx1aoBai** [comment]
![Screenshot_20240611_113005](https://github.com/Tencent/tdesign-flutter/assets/97790229/0d066d71-6f5d-41b2-b37f-8ade500c08f1)

**Comment by Luozf12345** [comment]
0.1.7已支持
