### ISSUE TITLE
[TDBottomTabBar] 使用原生AdaptiveLayout这个组件的时候 去嵌套TDBottomTabBar组件时候，始终会存在间距

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-flutter#171]
### tdesign-flutter 版本

^0.1.5

### 期望结果

没有间距

### 实际结果

![d0fff1ac2eff16e9bcdf9d59c2dadd5](https://github.com/Tencent/tdesign-flutter/assets/34641313/5e98fd52-9d6b-45fd-8c95-d9f3a822b74f)

### Flutter版本

 3.22.1

### 设备与机型信息

android

**Comment by Luozf12345** [comment]
我们本地未复现，请问有没有可能是SlotLayout导致的呢？请问你依赖的是哪个版本？我们尝试复现一下吧

**Comment by Luozf12345** [comment]
未复现，未有新信息，先关闭
