### ISSUE TITLE
[TDSearchBar] focus之后光标错位

### ISSUE THREAD

**Issue by kuma0605** [Tencent/tdesign-flutter#176]
### tdesign-flutter 版本

0.1.5

### 重现步骤

![41718155336_ pic](https://github.com/Tencent/tdesign-flutter/assets/2958589/363c0d70-66de-480f-a021-b96d572351c8)
![51718155337_ pic](https://github.com/Tencent/tdesign-flutter/assets/2958589/07a151f4-6632-4c6c-ac0e-c8f565be943a)

### 期望结果

光标对齐

### 实际结果

输入框光标错位

### Flutter版本

Flutter(3.19.6)

### 设备与机型信息

Android(Redmi Note 12)

### 系统版本

Android 14

**Comment by Luozf12345** [comment]
问题已定位到，预计0.1.7版本修复

**Comment by Luozf12345** [comment]
已修复，将会随0.1.8发版
