### ISSUE TITLE
button组件在macos上面，按钮的文字没有上下居中

### ISSUE THREAD

**Issue by xiongzhaoxu** [Tencent/tdesign-flutter#18]
### tdesign-flutter 版本

0.1.1

### 重现步骤

button组件在macos上面，按钮的文字没有上下居中

### 期望结果

按钮的文字上下居中

### 实际结果

![iShot_2023-12-30_18 35 35](https://github.com/Tencent/tdesign-flutter/assets/6897602/841e9359-e854-4888-b633-f39ce1ab2eb1)

### Flutter版本

3.16

### 设备与机型信息

macos14.2

### 系统版本

macos14.2

### 补充说明

![iShot_2023-12-30_18 35 35](https://github.com/Tencent/tdesign-flutter/assets/6897602/5a8447bb-6609-4932-8ee6-d393252fd996)

**Comment by Luozf12345** [comment]
感谢反馈，目前TDFlutter主要适配移动端应用，桌面端UI计划在今年内逐渐适配完善，感谢您的关注~

**Comment by xiongzhaoxu** [comment]
> 感谢反馈，目前TDFlutter主要适配移动端应用，桌面端UI计划在今年内逐渐适配完善，感谢您的关注~

好的，期待
