### ISSUE TITLE
TDImageViewer 图片预览组件

### ISSUE THREAD

**Issue by ccXxx1aoBai** [Tencent/tdesign-flutter#186]
## 组件名称中英文
图片预览组件

### 设计稿

设计稿：
<img width="375" alt="Preview 图片预览 移动端展示" src="https://github.com/Tencent/tdesign-flutter/assets/97790229/811744b3-6b0a-4f56-bf7c-693b4cc4a17f">

截图：

![Screenshot_20240614_230504](https://github.com/Tencent/tdesign-flutter/assets/97790229/2154786d-a827-413f-90c6-c599993c3cc2)
![Screenshot_20240614_231315](https://github.com/Tencent/tdesign-flutter/assets/97790229/6067e8f1-de04-4a04-bab2-5f3e337fa2a1)

### 参与贡献

如果你想要认领组件开发，请在本 issue 中评论认领并预估提交 PR 时间，例：

> “我认领这个组件 tdesign-flutter 仓库的实现任务，预计 x 日后提交”
请尽量在预期时间内完成，超期后 PMC 同学可能会联系其他同学接手实现。

详细提交过程请参考：[如何贡献](https://github.com/TDesignOteam/tdesign-flutter)。

欢迎填写[《贡献者加入意向收集》](https://wj.qq.com/s2/9772260/7cbe/)问卷加入 TDesign 贡献者群，参与过程中遇到的各类问题可以得到实时解答和指引。

**Comment by Luozf12345** [comment]
0.1.6已支持
