### ISSUE TITLE
[CountDown] 支持正向增加时间吗？需要用countUp的功能

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#189]
### 这个功能解决了什么问题

需要使用countUp的功能，UI和CountDown一致，但时间是正向增加的。

### 你建议的方案是什么

新增TimeCounter组件，由参数控制down/up

**Comment by epoll-j** [comment]
认领该issue，预计3天后提交

**Comment by Luozf12345** [comment]
0.1.7已支持
