### ISSUE TITLE
犀牛鸟专属-Link 演示代码拆分

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#204]
问题：点击查看Link的演示代码，看不到TDLink的具体用法。
任务：请参考TDButton的示例代码，让演示代码中可以看到TDLink的用法示例
验收标准：向主项目提pr，并附上代码的简单介绍或思考；演示代码拆分合理、可读性高、必要时添加合理注释。

*windows系统暂不支持演示代码的脚本，按照规则写好代码即可，无需本地生成演示代码资源。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/48ac8977-026d-4586-a399-c8483a8bab41)

参考界面：

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/03898d22-aba0-4fdd-a3cc-c320b730c713)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by BlackWinds05** [comment]
多人竞赛-已成功认领本issue
