### ISSUE TITLE
犀牛鸟专属-Slider 演示代码拆分

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#205]
问题：Slider的“组件状态”和“特殊样式”下面，多个演示组件使用同一份演示代码，演示代码太长，可读性不高。
任务：请参考上方“组件类型”的示例代码，拆分成每个组件对应一段演示代码。
验收标准：向主项目提pr，并附上代码的简单介绍或思考；演示代码拆分合理、可读性高、必要时添加合理注释。

*windows系统暂不支持演示代码的脚本，按照规则写好代码即可，无需本地生成演示代码资源。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/8f7a36cc-11f0-444d-94cc-3dbd43b1d8ce)

参考界面：
![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/fffd40b8-48e8-4d22-b523-e97fed7203a6)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by iamitis** [comment]
已成功领取本issue
