### ISSUE TITLE
犀牛鸟专属-Image 演示代码拆分

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#207]
问题：Image的“组件类型”和“组件状态”下面，多个演示组件使用同一份演示代码，演示代码太长，可读性不高。
任务：请参考Button“组件类型”的示例代码，拆分成每个组件对应一段演示代码。
验收标准：向主项目提pr，并附上代码的简单介绍或思考；演示代码拆分合理、可读性高、必要时添加合理注释。

*windows系统暂不支持演示代码的脚本，按照规则写好代码即可，无需本地生成演示代码资源。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/b66b520e-b843-48c7-a607-47c5b59b58d1)

参考界面：
![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/95ccece1-8488-418a-8c72-eddf2e70ae66)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by plus7c** [comment]
已成功领取本issue

**Comment by plus7c** [comment]
pr的背景信息有相关模板吗？

**Comment by plus7c** [comment]
请问提交pr的背景信息有模板吗？

**Comment by plus7c** [comment]
已提交pr
