### ISSUE TITLE
犀牛鸟专属-Switch 自定义“开/关”字体大小

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#208]
问题：Switch组件支持自定义文字，但当前字体大小是固定的，用户如果想把文字改小点，不支持修改。
任务：请参考Switch组件的thumbContentOnColor属性，增加thumbContentOnFont和thumbContentOffFont，实现修改字体大小的功能，并在Switch示例页的“单元测试”栏目下，增加使用示例。
验收标准：代码功能正常，使用示例清晰体现功能特性。

*windows系统暂不支持演示代码和API生成的脚本，按照规则写好代码即可，无需本地生成演示代码与API文档。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/7174b5ba-da5b-4a45-9c87-6dd9f5cc324e)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by shinyina** [comment]
已成功领取本issue

**Comment by destinyld** [comment]
已成功领取本issue
