### ISSUE TITLE
犀牛鸟专属-Search 添加action和onActionClick属性

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#209]
问题：Search组件不支持自定有右侧文字和文字的点击操作。
任务：请参考Search组件的其他属性实现，增加action和onActionClick属性,并在Search示例页的“单元测试”栏目下，增加使用示例。
action：表示自定义右侧操作按钮文字，如“取消”；
onActionClick：表示右侧操作内容点击时的响应。
注：如果未设置相关属性，则使用默认逻辑，与当前保持一致。
验收标准：代码功能正常，使用示例清晰体现功能特性。

*windows系统暂不支持演示代码和API生成的脚本，按照规则写好代码即可，无需本地生成演示代码与API文档。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/da600568-9ece-4536-be8b-a28d98377833)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by destinyld** [comment]
已成功领取本issue
