### ISSUE TITLE
犀牛鸟专属-Badge设置封顶的数字值

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#210]
问题：Badge组件当前value可以只能直接显示设置的内容，不支持“超过99的显示99+”类似的场景。
任务：请参考Badge组件的其他属性实现，增加maxCount属性,如果设置的count数值超过maxCount,则显示成"${maxCount}+"；并在Badge示例页的“单元测试”栏目下，增加使用示例。
验收标准：代码功能正常，使用示例清晰体现功能特性。

*windows系统暂不支持演示代码和API生成的脚本，按照规则写好代码即可，无需本地生成演示代码与API文档。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/669d2997-0bab-402c-ada0-e1313ec5487d)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by chendingya** [comment]
已成功领取本issue

**Comment by chendingya** [comment]
“在Search示例页的“单元测试”栏目下，增加使用示例。”这个是不是写错了，应该在badge的单元测试栏目？
@Luozf12345
