### ISSUE TITLE
犀牛鸟专属-”关于我们“页面增加发版日期

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#211]
问题：当前“关于我们”页面，只有版本号，没有发版日期，不方便确定example是否为比较旧的版本。
任务：请参考版本号的实现代码，增加pulish_time文件，记录发版时间戳，并在“关于我们”页面，按照"2024-6-25"的格式展示
验收标准：代码功能正常。
![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/091c291f-c845-4dc4-b20f-961203781c09)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by iamitis** [comment]
已成功领取本issue
