### ISSUE TITLE
犀牛鸟专属-新增 Result 组件

### ISSUE THREAD

**Issue by Luozf12345** [Tencent/tdesign-flutter#212]
问题：按照设计稿完成Result组件开发，设计稿地址：https://codesign.qq.com/s/332865
验收标准：
●支持设计稿示例的所有状态
●按照“Result 结果 移动端展示”实现示例页面
●设计走查通过
●演示代码拆分合理、可读性高

*windows系统暂不支持演示代码和API生成的脚本，按照规则写好代码即可，无需本地生成演示代码与API文档。*

![image](https://github.com/Tencent/tdesign-flutter/assets/35024333/68e736dc-fa32-4569-be01-c66e457531e5)

**本issue为2024犀牛鸟开源人才培养活动专属issue，仅供在校大学生参与领取**
【认领issue】在[研学基地](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D)"issue营地"对应issue行的M~R列**抢滩报名**，即视为**认领成功**。
【完成issue】已认领issue的同学，请同步在本issue评论区回复“已成功领取本issue”； 如7天内无提交任何进展包括不限于comment \ commit \ Pull Request，则将视为同学主动放弃issue，组委会将释放issue给下一位等候者。
https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D?tab=BB08J2

**Comment by shinyina** [comment]
已成功领取本issue
