### ISSUE TITLE
TDButtonStyle 无法只改变Border颜色

### ISSUE THREAD

**Issue by Venali2233** [Tencent/tdesign-flutter#225]
### tdesign-flutter 版本

0.1.5

### 补充说明

由于TDButtonStyle不能copyWith如果改变Border颜色，  style: TDButtonStyle(  frameColor: buttonBorderColor, frameWidth: 0.5),那么原本的点击样式就会失效，点击后背景无任何颜色改变，需要自行监听是否点击。能否优化如果改TDButtonStyle属性，只改变指定的属性，

**Comment by Luozf12345** [comment]
当前版本已可实现。可以先生成默认Style，再修改自定义参数，例如以下写法：
TDButtonStyle.generateFillStyleByTheme(context, TDButtonTheme.primary, TDButtonStatus.active)
    ..textColor = Colors.red
