### ISSUE TITLE
[Image Preview] 有没有图片和视频的预览组件，对齐微信的那种

### ISSUE THREAD

**Issue by fuyuku** [Tencent/tdesign-flutter#23]
### 这个功能解决了什么问题

目前没有发现好用的图片和视频的预览组件，有没有添加的计划

### 你建议的方案是什么

这个组件应该是很常见的，看vue上有这个，flutter版本有计划支持吗？

**Comment by Luozf12345** [comment]
目前还没有，不过有不少同学提出了需求，后面团队评估一下支持方案
