### ISSUE TITLE
建议重新设计

### ISSUE THREAD

**Issue by virskor** [Tencent/tdesign-flutter#24]
虽然UI库很好看但是并没有继承Flutter的设计思维。首先没有使用ThemeData, 这样导致用户需要单独再去声明一套tdesign的themeData，此外，耦合严重，为什么要耦合easy refresh等组件呢？很多问题

**Comment by Luozf12345** [comment]
声明tdesign的themeData，是为了主题token与tdesign其他技术栈的保持一致，方便风格统一，以及后续复用主题自动生成等能力。至于系统的ThemeData，目前是可以同时使用的，后续看下怎么把TDhemeData的属性转换过来，方便大家更平滑地迁移项目。
