### ISSUE TITLE
[TDSideBar] 如果children内的数据是通过接口获取的，则无法正常渲染

### ISSUE THREAD

**Issue by carrot7454** [Tencent/tdesign-flutter#256]
### tdesign-flutter 版本

0.1.5

### 重现步骤

1. 使用官方案例中示例可以正常渲染
2. 
![image](https://github.com/user-attachments/assets/9b164d80-6a07-4015-88f8-1d53bb5d96b4)
![image](https://github.com/user-attachments/assets/5e29a046-3ff9-4a16-8566-8700b2b09e5b)
![image](https://github.com/user-attachments/assets/e63ce2b1-c8f0-428a-809c-72fb9d78a125)
![image](https://github.com/user-attachments/assets/d7b70d1c-27a9-4cb5-ae48-050a0201d8ce)
数据是从接口里拿的，而且也能打印出来，但是页面渲染不出来

### 期望结果

能够正常渲染

### 实际结果

无法正常渲染

**Comment by ccXxx1aoBai** [comment]
可以试下把setState放到第二张图片for循环后面

**Comment by carrot7454** [comment]
> 可以试下把setState放到第二张图片for循环后面

可以了，感谢

**Comment by soxft** [comment]
如果是第二张图 list直接 add 可能会造成 flutter 无法检测到变更
试试用 `list = [...list, SideItemProps()]`

**Comment by carrot7454** [comment]
> 如果是第二张图 list直接 add 可能会造成 flutter 无法检测到变更 试试用 `list = [...list, SideItemProps()]`

![image](https://github.com/user-attachments/assets/fda384ce-8b00-4d5f-9193-ae6ffd41c6ac)
已改，但是还是restart的时候出不来

**Comment by soxft** [comment]
> > 如果是第二张图 list直接 add 可能会造成 flutter 无法检测到变更 试试用 `list = [...list, SideItemProps()]`
> 
> ![image](https://private-user-images.githubusercontent.com/47313062/353322163-fda384ce-8b00-4d5f-9193-ae6ffd41c6ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTc3MjgsIm5iZiI6MTcyMjMxNzQyOCwicGF0aCI6Ii80NzMxMzA2Mi8zNTMzMjIxNjMtZmRhMzg0Y2UtOGIwMC00ZDVmLTkxOTMtYWU2ZmZkNDFjNmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA1MzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjllODIzYjIzZTA4Y2Q4ZjZiZjM0OTJlMzViMTlmNWU2Yjg4YWM3Zjg4MzNmYTlkNWYxYzFlODNhYzI5ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZBfdvrBQBT7H1JUnYbvJtTRHbUf3Zsk_EOZirkFkfM) 已改，但是还是restart的时候出不来

TDSidebar 通过在首次初始化时，在 initStatus 中 将 `widget.children` 转换成内部变量 `displayChildren` 后渲染 因此无法感知父组件 children 变化而 刷新子组件

https://github.com/Tencent/tdesign-flutter/blob/f6837f6ced2a513227a843fcb428bab1f8828948/tdesign-component/lib/src/components/sidebar/td_sidebar.dart#L140-L151

可以通过 didUpdateWidget 等方式，监听 widget.children 变化后，更新 displayChildren

**Comment by ccXxx1aoBai** [comment]
restart也得调用setState()

**Comment by ccXxx1aoBai** [comment]
flutter不像vue那样响应式数据，需要通过触发build()来更新

**Comment by soxft** [comment]
> restart也得调用setState()

好家伙 不太懂
能否帮忙看一下 写了个demo   `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢

**Comment by ccXxx1aoBai** [comment]
> > restart也得调用setState()
> 
> 好家伙 不太懂 能否帮忙看一下 写了个demo `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢

我看demo没问题

**Comment by soxft** [comment]
> > > restart也得调用setState()
> > 
> > 
> > 好家伙 不太懂 能否帮忙看一下 写了个demo `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢
> 
> 我看demo没问题，建议可以把变量放到setState函数体里面

运行起来确实会遇到 问题

当 picker 处于打开的状态下，再在 父组件更新数据。 picker内 没有渲染新的数据。


https://github.com/user-attachments/assets/67c89291-8f58-4277-afa3-f74c5416fde1

**Comment by ccXxx1aoBai** [comment]
> > > > restart也得调用setState()
> > > 
> > > 
> > > 好家伙 不太懂 能否帮忙看一下 写了个demo `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢
> > 
> > 
> > 我看demo没问题，建议可以把变量放到setState函数体里面
> 
> 运行起来确实会遇到 问题
> 
> 当 picker 处于打开的状态下，再在 父组件更新数据。 picker内 没有渲染新的数据。
> 
>  2024-07-30.15.33.05.mov

因为这是两个页面，setState只作用于当前页

**Comment by ccXxx1aoBai** [comment]
> > > > > restart也得调用setState()
> > > > 
> > > > 
> > > > 好家伙 不太懂 能否帮忙看一下 写了个demo `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢
> > > 
> > > 
> > > 我看demo没问题，建议可以把变量放到setState函数体里面
> > 
> > 
> > 运行起来确实会遇到 问题
> > 当 picker 处于打开的状态下，再在 父组件更新数据。 picker内 没有渲染新的数据。
> > 2024-07-30.15.33.05.mov
> 
> 因为这是两个页面，setState只作用于当前页

你这个需求是啥情景，不能先获取数据在打开吗

**Comment by soxft** [comment]
> > > > > > restart也得调用setState()
> > > > > 
> > > > > 
> > > > > 好家伙 不太懂 能否帮忙看一下 写了个demo `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢
> > > > 
> > > > 
> > > > 我看demo没问题，建议可以把变量放到setState函数体里面
> > > 
> > > 
> > > 运行起来确实会遇到 问题
> > > 当 picker 处于打开的状态下，再在 父组件更新数据。 picker内 没有渲染新的数据。
> > > 2024-07-30.15.33.05.mov
> > 
> > 
> > 因为这是两个页面，setState只作用于当前页
> 
> 你这个需求是啥情景，不能先获取数据在打开吗

主要是 按照题主的思路吧 ( 可以先 展示一个 loading 等待加载完后 再打开

**Comment by ccXxx1aoBai** [comment]
> > > > > > > restart也得调用setState()
> > > > > > 
> > > > > > 
> > > > > > 好家伙 不太懂 能否帮忙看一下 写了个demo `https://github.com/soxft/TDCascader/tree/td_sidebar` 感谢
> > > > > 
> > > > > 
> > > > > 我看demo没问题，建议可以把变量放到setState函数体里面
> > > > 
> > > > 
> > > > 运行起来确实会遇到 问题
> > > > 当 picker 处于打开的状态下，再在 父组件更新数据。 picker内 没有渲染新的数据。
> > > > 2024-07-30.15.33.05.mov
> > > 
> > > 
> > > 因为这是两个页面，setState只作用于当前页
> > 
> > 
> > 你这个需求是啥情景，不能先获取数据在打开吗
> 
> 主要是 按照题主的思路吧 ( 可以先 展示一个 loading 等待加载完后 再打开

先弹出，再显示值，这个需要改造组件

**Comment by Luozf12345** [comment]
0.1.7版本已支持
