### ISSUE TITLE
[TDCascader] 多层级引起的无法选择

### ISSUE THREAD

**Issue by soxft** [Tencent/tdesign-flutter#258]
### tdesign-flutter 版本

0.1.5

### 重现链接

https://github.com/soxft/TDCascader

### 重现步骤

如Demo中 在行政部门/部门一/张雷1 下 新增一个层级
将无法选中 行政部门/部门一/xxx 的其他用户

<img width="440" alt="image" src="https://github.com/user-attachments/assets/1310fb90-0343-4dbe-a5e0-8c25457c804c">

### 期望结果

![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-26 at 00 01 18](https://github.com/user-attachments/assets/8771bacd-a1f0-40fd-9fec-10e963742ade)

### 实际结果

![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-26 at 00 02 08](https://github.com/user-attachments/assets/4355fe2c-34ef-4682-b31a-827e74842a40)
无法选中

### Flutter版本

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git Framework • revision 761747bfc5 (7 weeks ago) • 2024-06-05 22:15:13 +0200 Engine • revision edd8546116 Tools • Dart 3.4.3 • DevTools 2.34.3

### 设备与机型信息

ios simulator

### 系统版本

IOS 18.0

### 补充说明

需要设计 部门多层级选择

**Comment by soxft** [comment]
似乎只能选择到最深一层。 但是实际情况下 对于企业部门而言，可能存在某一部门下 更细的子部门划分

**Comment by Luozf12345** [comment]
好的，感谢反馈，我们下个版本会去掉层级限制，支持数据结构指定的层级。不过层级过深可能会引起性能问题，不建议设置太深的层级。
