### ISSUE TITLE
可以新增任意组件的跑马灯组件吗？

### ISSUE THREAD

**Issue by hanxiaofeng** [Tencent/tdesign-flutter#26]
### 这个功能解决了什么问题

内容过多时使用，循环展示

### 你建议的方案是什么

暂无

**Comment by Luozf12345** [comment]
跑马灯的话，文字类型的比较好支持，任意组件类型的话，我们需要讨论一下怎么实现。短期内可能只能先支持文字类型的，我们下个版本评估下吧。
