### ISSUE TITLE
[TDPicker] 无法修改弹出框顶部文字颜色

### ISSUE THREAD

**Issue by ccXxx1aoBai** [Tencent/tdesign-flutter#269]
### tdesign-flutter 版本

0.1.6

### 补充说明

TDPicker中showDatePicker、showMultiPicker、showMultiLinkedPicker无法修改顶部文字颜色，如果需要修改颜色需要自己编写弹出逻辑，通过TDDatePicker、TDMultiPicker、TDMultiLinkedPicker对应属性设置文字颜色

**Comment by Luozf12345** [comment]
0.1.7已支持
