### ISSUE TITLE
[TDCell] 增加一个上下边距自定义尺寸的选项

### ISSUE THREAD

**Issue by 988494** [Tencent/tdesign-flutter#275]
### 这个功能解决了什么问题

有时候 TDCell 自带的上下边距太大了
![image](https://github.com/user-attachments/assets/a973138f-d68f-4f58-8135-d709d6ffb5e1)

### 你建议的方案是什么

建议增加一个参数选项

**Comment by Luozf12345** [comment]
0.1.7已支持
