### ISSUE TITLE
[组件名称] 描述问题的标题 Because sfeapp depends on tdesign_flutter ^0.1.6 which depends on flutter_slidable 3.1.0, flutter_slidable 3.1.0 is required

### ISSUE THREAD

**Issue by supermebing** [Tencent/tdesign-flutter#277]
### tdesign-flutter 版本

0.1.6

### 重现步骤

Because sfeapp depends on tdesign_flutter ^0.1.6 which depends on flutter_slidable 3.1.0, flutter_slidable 3.1.0 is required

**Comment by ccXxx1aoBai** [comment]
手动引入一下flutter_slidable，之前swiper有这个问题
