### ISSUE TITLE
[Picker 选择器] TDMultiPicker的topPadding和titleDividerColor属性无效

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-flutter#285]
### tdesign-flutter 版本

0.1.6

### 重现步骤

![image](https://github.com/user-attachments/assets/dc438642-3462-4605-bf5b-4098408cfaef)

### 期望结果

有分割线

### 实际结果

没有分割线

### Flutter版本

3.22.2

### 设备与机型信息

oppo a9

**Comment by Luozf12345** [comment]
0.1.7已支持
