### ISSUE TITLE
[Dialog 对话框] 希望开放TDDialogScaffold组件及其配套下的组件 以支持更加灵活的多变的需求，如自定义按钮宽度，内容的的内边距控制及按钮和内容之间的距离等

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-flutter#288]
### 这个功能解决了什么问题

[Dialog 对话框] 希望开放TDDialogScaffold组件及其配套下的组件 以支持更加灵活的多变的需求，如自定义按钮宽度，内容的的内边距控制及按钮和内容之间的距离等

### 你建议的方案是什么

开放TDDialogScaffold组件及其配套下的组件

**Comment by Luozf12345** [comment]
0.1.7已支持
