### ISSUE TITLE
[TDButton] 在TDButton的onTap中同步执行Navigator.of(context).pushNamedAndRemoveUntil()方法会抛出异常：FlutterError (setState() called after dispose(): _TDButtonState#9cc4e(lifecycle state: defunct, not mounted)    

### ISSUE THREAD

**Issue by jgyhc** [Tencent/tdesign-flutter#29]
### tdesign-flutter 版本

0.1.2

### 重现步骤

[TDButton] 在TDButton的onTap中同步执行Navigator.of(context).pushNamedAndRemoveUntil()方法会抛出异常：FlutterError (setState() called after dispose(): _TDButtonState#9cc4e(lifecycle state: defunct, not mounted)    

### 期望结果

延时执行可以避免，希望可以修复一下。

**Comment by Luozf12345** [comment]
感谢反馈，我们排查一下，尽快在下个版本修复

**Comment by Luozf12345** [comment]
你好，我这边没有复现出来，请问能提供一下Flutter SDK版本，以及具体代码写法吗？我在0.1.3里添加了该场景的测试用例，可以看下复现用例与你的代码有何差异吧~
<img width="1126" alt="image" src="https://github.com/Tencent/tdesign-flutter/assets/35024333/6ab605c3-5917-428b-823a-f93ef849ad37">


这个issue先关闭了，如果有任何问题，欢迎在官方群里反馈，我们会及时响应
