### ISSUE TITLE
[TDImageViewer] defaultIndex设置默认的index后，下一张或者上一张不是从defaultIndex开始计算

### ISSUE THREAD

**Issue by wanghui159753** [Tencent/tdesign-flutter#293]
### tdesign-flutter 版本

0.1.6

### 重现链接

无

### 重现步骤

 TDImageViewer.showImageViewer(
             context: context,
             images: imageUrls,
             defaultIndex:imageUrls.indexOf(element)+1,
             showIndex: true
          );

### 期望结果

使用defaultIndex作为初始滑动索引

### 实际结果

初始滑动索引为0

### Flutter版本

3

### 设备与机型信息

all

### 补充说明

无

**Comment by Luozf12345** [comment]
0.1.7已支持
