### ISSUE TITLE
[TDCascader] 横向级联选择器，列表数据第一组数据无法展示/未展示

### ISSUE THREAD

**Issue by fight-ing** [Tencent/tdesign-flutter#295]
### tdesign-flutter 版本

0.1.6

### 重现步骤

TDCascader.showMultiCascader(context,
                      title: "地址选择",
                      data: controller.areaList,
                      initialIndexes: [0,0,0],
                      
                      theme: "tab",
                      onChange: (List<MultiCascaderListModel> selectData) {

                    int len = selectData.length;
                    if (len >= 1) {
                      List result = [];
                      controller.initDataManage(selectData[len - 1].value!);
                      selectData.forEach((element) {
                        result.add(element.label);
                      });
                      controller.selectDataManage(result.join('/'));
                    }

                  }, onClose: () {
                    Navigator.of(context).pop();
                  });

![WechatIMG2977](https://github.com/user-attachments/assets/08cf7abf-7429-4663-a39b-1956ba0a0531)

### 期望结果

展示List全部数据

**Comment by fight-ing** [comment]
[area_data2.json](https://github.com/user-attachments/files/16609632/area_data2.json)

读取本地的JSON文件
List<dynamic> tList =
          await HttpMock.getMockDataWithPath(path: "res/json/area_data.json");

      List<Map<String,dynamic>> jsonList = covertAddressData(tList);
      debugPrint(jsonList.toString());

打印的List数据是有“北京”的，但是选择器没有

**Comment by fight-ing** [comment]
![1723686993198](https://github.com/user-attachments/assets/3620fbde-bcf2-42b4-b927-c5112ffdb5ac)
数据没有丢失，第一条被插到后面，顺序不对，List数据顺序和现实的顺序有出入，不确定原因，目前只有第一个北京被插入到中间。

**Comment by shizhe2018** [comment]
bug已修复，待版本发布

**Comment by fight-ing** [comment]
多久，赶不及发布就换了

**Comment by Luozf12345** [comment]
新版本大概在9月中旬发布；在新版本发布之前，已修复的bug可以通过在yaml指定依赖develop分支来解决。

**Comment by Luozf12345** [comment]
0.1.7已支持
