### ISSUE TITLE
[组件名称] TDSlider改变value滑块不会变化

### ISSUE THREAD

**Issue by lym95** [Tencent/tdesign-flutter#296]
### tdesign-flutter 版本

0.1。6

### 重现步骤

![cfcf7ca118f273a74745dd81f2ca4c8](https://github.com/user-attachments/assets/1801c879-09a0-40cf-8cd0-ac9ff60a7466)
滑块不根据数值的变化而变化
![638eb2c599a460025a4bc709372bd41](https://github.com/user-attachments/assets/887b70b4-09ca-4157-9a19-82af9be748f6)

### 期望结果

滑块数值的变化而变化

### 实际结果

滑块不根据数值的变化而变化

**Comment by Luozf12345** [comment]
0.1.7已支持
