### ISSUE TITLE
[Cell] 能嵌套Input组件

### ISSUE THREAD

**Issue by xiaodel** [Tencent/tdesign-flutter#306]
### 这个功能解决了什么问题

现在还没有form组件，希望能通过Cell充当formItem的角色能嵌套其他表单组件

### 你建议的方案是什么

noteWidget属性或者rightIconWidget属性能够套入其他表单型组件

![image](https://github.com/user-attachments/assets/890dcfcd-5bb9-4766-8953-165381131827)

**Comment by ccXxx1aoBai** [comment]
可以把input放到titleWidget里面，input可以设置label不会占用cell的title
![image](https://github.com/user-attachments/assets/55b673c2-1db4-45ae-8f42-8c566a4115cd)
