### ISSUE TITLE
[Search 搜索框] 搜索框状态(焦点)获取及清除事件

### ISSUE THREAD

**Issue by 315574925** [Tencent/tdesign-flutter#309]
### 这个功能解决了什么问题

如我要根据状态，控制页面是否显示搜索历史记录或者热搜功能，输入状态我就显示搜索历史记，清除搜索框内容后有回调事件

### 你建议的方案是什么

开放 focusNode 属性 或者增加一个回调方法

**Comment by Luozf12345** [comment]
0.1.7已支持
