### ISSUE TITLE
[TDTabBar] indicatorColor: Colors.red,使用后下标不会变颜色

### ISSUE THREAD

**Issue by boy-yu** [Tencent/tdesign-flutter#31]
### tdesign-flutter 版本

0.1.1

### Flutter版本

Flutter(3.10.3)

### 设备与机型信息

Android 13

**Comment by Luozf12345** [comment]
感谢反馈，我们确认一下，尽快在下个版本优化

**Comment by Luozf12345** [comment]
0.1.3版本已修复
