### ISSUE TITLE
[弹出层] 快速点击蒙层执行多次返回, 导致白屏

### ISSUE THREAD

**Issue by BangBrother** [Tencent/tdesign-flutter#315]
### tdesign-flutter 版本

0.1.6

### 重现链接

https://tdesign.tencent.com/flutter/components/popup

### 重现步骤

官方文档https://tdesign.tencent.com/flutter/components/popup右边的示例即可重现. 快速点击蒙层或确定按钮会执行多次点击事件,导致执行多次返回操作并白屏.

**Comment by shizhe2018** [comment]
是什么机型，按照你操作流程，没有白屏

**Comment by Luozf12345** [comment]
0.1.7已支持
