### ISSUE TITLE
折线图 等相关图表

### ISSUE THREAD

**Issue by songangweb** [Tencent/tdesign-flutter#319]
### 这个功能解决了什么问题

现在开源项目中的 有关统计图相关的项目甚少。

### 你建议的方案是什么

希望能出一些统计图标，  尤其是折线图  相关的， 像腾讯云对服务服务器资源统计的 折线图   觉得可以直接移植过来

**Comment by gailiuziaa007** [comment]
这个用的比较多啊, 很需要啊

**Comment by Luozf12345** [comment]
短时间暂时没有图表类组件规划，后续是否增加可能要看25年的具体情况。
