### ISSUE TITLE
[TDInput] rightBtn存在默认间距，rightWidget仅在特殊类型时生效，特殊类型时会有一条默认的下划线，type: TDInputType.cardStyle 时没有默认下划线，但rightWidget不生效了

### ISSUE THREAD

**Issue by kumufeng** [Tencent/tdesign-flutter#32]
### tdesign-flutter 版本

0.1.2

### 期望结果

右侧组件支持自定义，可以有默认样式，但支持覆盖，其他的组件也可以如此，有一套默认样式，但也需要把自定义能力给到使用者

### 实际结果

右侧组件支持自定义，但有特殊限制

### Flutter版本

3.16.3

**Comment by Luozf12345** [comment]
感谢反馈，我们排查一下，会在下个版本尽快优化

**Comment by Luozf12345** [comment]
0.1.5版本已支持
