### ISSUE TITLE
[TDTabBar] 期望新增tabAlignment参数

### ISSUE THREAD

**Issue by gailiuziaa007** [Tencent/tdesign-flutter#325]
### 这个功能解决了什么问题

期望新增tabAlignment参数

### 你建议的方案是什么

期望新增tabAlignment参数

**Comment by ccXxx1aoBai** [comment]
可以描述一些使用场景吗

**Comment by gailiuziaa007** [comment]
> 可以描述一些使用场景吗

这个是原生的组件TabBar里面就有, 可以让tab从左往右排列,  不用去平分

**Comment by shizhe2018** [comment]
在处理了

**Comment by gailiuziaa007** [comment]
> 在处理了

谢谢

**Comment by Luozf12345** [comment]
请使用git依赖0.1.7_TabAlignment这个tag
