### ISSUE TITLE
[SideBar 侧边栏] 标题超过4个字符会遮挡

### ISSUE THREAD

**Issue by sineom-1** [Tencent/tdesign-flutter#326]
### tdesign-flutter 版本

最新版本

### 补充说明

实际业务中标题的长度不应该受限于组件，而是组件适配业务
<img width="533" alt="image" src="https://github.com/user-attachments/assets/f65b13e5-1383-4142-b3e0-c6068bed3be1">

**Comment by shizhe2018** [comment]
已在改进

**Comment by windinternet** [comment]
我感觉好多地方主要还是设计规范问题，好多字体粗细，大小，组件间距等等 不是很协调   希望大哥些跟设计师，再合计合计

**Comment by Luozf12345** [comment]
0.1.7已支持
