### ISSUE TITLE
[Tabs选项卡] 在outlineType线条样式类型设置为TDTabBarOutlineType.card时，切换选项卡时底部两侧会一瞬间出现蓝色又消失的bug

### ISSUE THREAD

**Issue by 211277729** [Tencent/tdesign-flutter#334]
### tdesign-flutter 版本

0.1.6

### 重现步骤

SizedBox(
                              height: 40,
                              child: TDTabBar(
                                labelColor: appColor.getAppMainColor(),
                                indicatorColor: appColor.getAppMainColor(),
                                outlineType: TDTabBarOutlineType.card,
                                tabs: const [
                                  TDTab(
                                    text: "文本",
                                  ),
                                  TDTab(
                                    text: "样式",
                                  ),
                                  TDTab(
                                    text: "对齐",
                                  ),
                                ],
                                controller: _tabController,
                                showIndicator: true,
                                backgroundColor: Colors.white,
                                isScrollable: false,
                              ),
                            )

### 期望结果

不显示颜色

### 实际结果

切换选项卡时底部两侧会一瞬间出现蓝色又消失的bug，类似切片的问题

### Flutter版本

3.19.6

### 设备与机型信息

vivo xFold3 Pro

### 系统版本

Android14

**Comment by shizhe2018** [comment]
将这个  indicatorColor属性设置  indicatorColor：Colors.transparent,

**Comment by Luozf12345** [comment]
回复解决后未有新反馈，先关闭
