### ISSUE TITLE
TDButton的文字没有垂直居中，设置背景颜色后格外明显[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by jgyhc** [Tencent/tdesign-flutter#35]
### tdesign-flutter 版本

0.1.2

### 重现步骤

![38825994C07CB14E78FEA2CEA899DCE2](https://github.com/Tencent/tdesign-flutter/assets/16422230/5423a042-47c2-463c-9bf2-86b568f5fa3b)

### 期望结果

希望可以解决不垂直居中的问题

**Comment by yangtianxia** [comment]
遇到相同问题，好像是TDText组件导致的，不知道什么是否可以修复？

![image](https://github.com/Tencent/tdesign-flutter/assets/73974709/cdd2f1bc-c36f-477c-bcb2-b564a46e2dbe)

**Comment by Luozf12345** [comment]
请问是在什么设备上运行的呢？Flutter官方没有支持中文居中能力，TD之中提供了TDTextConfiguration和CustomTextPaddingConfig来运行修改内部填充比例，使文字居中，不过部分机型（比如三星）的比例可能与其他机型不一样，需要自己处理。

**Comment by Luozf12345** [comment]
应该是Flutter3.16以后得渲染引擎改变导致的问题，0.1.4版本会先添加一个禁用forceVerticalCenter功能的开关，让TD的字体可以与官方保持一致。文本居中的通用适配方案后面再看下怎么处理吧
