### ISSUE TITLE
[TDCell] 自定义左边 icon后, 单行无法文本无法居中

### ISSUE THREAD

**Issue by jackson0122** [Tencent/tdesign-flutter#358]
### tdesign-flutter 版本

 0.1.7

### 重现步骤

  Widget _buildView() {
    return ListView.separated(
      itemCount: 27,
      separatorBuilder: (context, index) => TDDivider(
        color: Color(0xFFEAEAEA),
      ),
      itemBuilder: (context, index) => TDCellGroup(title: 'A', cells: [
        TDCell(
          title: '我是第$index个',
          leftIconWidget: TDAvatar(
            avatarSize: 50,
            avatarUrl:
                "http://gips2.baidu.com/it/u=195724436,3554684702&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960",
          ),
        ),
        TDCell(
          title: '我是第$index个',
          leftIconWidget: TDAvatar(
            avatarSize: 50,
            avatarUrl:
                "http://gips2.baidu.com/it/u=195724436,3554684702&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960",
          ),
        )
      ]),
    );
  }

![image](https://github.com/user-attachments/assets/e34439a0-ed51-4142-af26-b65d3baf71ef)

**Comment by shizhe2018** [comment]
设计如此，使用这个      TDCell(
        title: '我是第2个',
        image:NetworkImage("http://gips2.baidu.com/it/u=195724436,3554684702&fm=3028&app=3028&f=JPEG&fmt=auto?w=1280&h=960"),
      ),
