### ISSUE TITLE
[TDAvatar] 自定义头像大小 avatarSize 变形问题

### ISSUE THREAD

**Issue by iscodeok** [Tencent/tdesign-flutter#359]
### tdesign-flutter 版本

0.1.5

### 重现步骤

[TDAvatar] 自定义头像大小 avatarSize 设置小于 40.0 时，头像会变形比例不对。

### Flutter版本

Flutter 3.24.0

### 设备与机型信息

Android 12~13 模拟器

### 系统版本

Android

**Comment by shizhe2018** [comment]
麻烦提供一个变形截图，目前通过提供的设置属性值，测试没有发现变形

**Comment by iscodeok** [comment]
@shizhe2018 找到问题了，是 Container 设置 width 或 padding会影响 TDAvatar 变形，可能不是BUG。
