### ISSUE TITLE
[TDInputDialog] 外部无法感知按钮的点击事件

### ISSUE THREAD

**Issue by sineom-1** [Tencent/tdesign-flutter#367]
### tdesign-flutter 版本

最新版本

### 重现步骤

![image](https://github.com/user-attachments/assets/b0187a01-4722-4afc-8cbb-d83a570b3245)

**Comment by ccXxx1aoBai** [comment]
默认按钮不支持自定义事件，如果需要，请自定义按钮
![QQ_1730338213258](https://github.com/user-attachments/assets/8821c0e8-484d-49c8-a9c1-0d6af2fdd98f)
