### ISSUE TITLE
Error: The method 'hashValues' isn't defined for the class 'TDCollapseSaltedKey<S, V>'

### ISSUE THREAD

**Issue by StephenCMZ** [Tencent/tdesign-flutter#368]
### tdesign-flutter 版本

0.1.7

### 重现步骤

1. flutter pub add tdesign_flutter
2. flutter run 

### 期望结果

无错误，正常运行

### 实际结果

![WeChat263d4914ffe7b0c9d072e3b1e6a5635c](https://github.com/user-attachments/assets/eeffa709-983b-42e3-8630-99bd9fa3da53)

### Flutter版本

3.27.0-1.0.pre.257

**Comment by shizhe2018** [comment]
待下一个版本发布

**Comment by Zhanweelee** [comment]
Same problem for "flutter_slidable", please upgrade flutter_slidable to version above 3.1.2, thanks


/Users/local/.pub-cache/hosted/pub.dev/flutter_slidable-3.1.0/lib/src/notifications_old.dart:88:23: Error: The method 'hashValues' isn't defined for the class 'SlidableRatioNotification'.
