### ISSUE TITLE
[TDTextarea] 组件下划线无法隐藏

### ISSUE THREAD

**Issue by sineom-1** [Tencent/tdesign-flutter#371]
### tdesign-flutter 版本

最新版本

### 重现步骤

![image](https://github.com/user-attachments/assets/a18d20f1-8fb9-4ca5-81c9-1488297b97cc)

### 期望结果

可以动态控制

### Flutter版本

最新

**Comment by ccXxx1aoBai** [comment]
这样写可以隐藏

![QQ_1731313328134](https://github.com/user-attachments/assets/752bbebf-b378-42e3-88f5-ef7cae72eff2)

**Comment by Luozf12345** [comment]
已提供解决方案，先关闭
