### ISSUE TITLE
[TDTextarea] 字数限制的文本展示应该由组件内部控制，而不是由外部触发

### ISSUE THREAD

**Issue by sineom-1** [Tencent/tdesign-flutter#384]
### tdesign-flutter 版本

最新版本

### 实际结果

<img width="1994" alt="image" src="https://github.com/user-attachments/assets/5d2e11ea-0aea-4eaf-8dfc-41b420621a00">

### Flutter版本

最新

**Comment by shizhe2018** [comment]
已优化，待下一个版本发布
