### ISSUE TITLE
[TDRadio] 水平排列会强制添加下划线

### ISSUE THREAD

**Issue by sineom-1** [Tencent/tdesign-flutter#39]
### tdesign-flutter 版本

0.1.2

### 重现步骤

<img width="1243" alt="image" src="https://github.com/Tencent/tdesign-flutter/assets/14144748/a50a2f0e-4f38-421d-a079-5f619bbfbba9">

### 期望结果

showDivider字段可以控制下划线

**Comment by Luozf12345** [comment]
0.1.3版本已修复
