### ISSUE TITLE
[td_collapse] 升级到 Flutter 3.27.0 导致编译失败

### ISSUE THREAD

**Issue by JackCui001** [Tencent/tdesign-flutter#400]
### tdesign-flutter 版本

0.1.7

### 重现步骤

flutter upgrade，升级 Flutter 至 3.27.0（Stable 分支最新版）

### 期望结果

正常编译

### 实际结果

编译报错：
> C:/Users/username/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/tdesign_flutter-0.1.7/lib/src/components/collapse/td_collapse_salted_key.dart:20:23: Error: The method 'hashValues' isn't defined for the class 'TDCollapseSaltedKey<S, V>'.
'TDCollapseSaltedKey' is from 'package:tdesign_flutter/src/components/collapse/td_collapse_salted_key.dart' ('/C:/Users/username/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/tdesign_flutter-0.1.7/lib/src/components/collapse/td_collapse_salted_key.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
int get hashCode => hashValues(runtimeType, salt, value);
                               ^^^^^^^^^^
/C:/Users/username/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_slidable-3.1.0/lib/src/notifications_old.dart:88:23: Error: The method 'hashValues' isn't defined for the class 'SlidableRatioNotification'.
'SlidableRatioNotification' is from 'package:flutter_slidable/src/notifications_old.dart' ('/C:/Users/username/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/flutter_slidable-3.1.0/lib/src/notifications_old.dart').
Try correcting the name to the name of an existing method, or defining a method named 'hashValues'.
int get hashCode => hashValues(tag, ratio);

### Flutter版本

3.27.0

### 设备与机型信息

Android (Redmi K20 Pro)

### 系统版本

Android 14

### 补充说明

flutter/flutter#151677
在 Flutter 主线分支的这个 PR 中，hashList 与 hashValues被废弃，可能是该错误的原因

**Comment by bomb-bomb** [comment]
出现同样的问题，可以给出修复时间吗？不行的话 只能先 fock 自己改了.

**Comment by JackCui001** [comment]
> 出现同样的问题，可以给出修复时间吗？不行的话 只能先 fock 自己改了.

我暂时先用 flutter downgrade 回退到 3.24.5 了，旧版本一切正常。

**Comment by bomb-bomb** [comment]
> > 出现同样的问题，可以给出修复时间吗？不行的话 只能先 fock 自己改了.
> 
> 我暂时先用 flutter downgrade 回退到 3.24.5 了，旧版本一切正常。

  tdesign_flutter:
    git:
      url: 'https://github.com/bomb-bomb/tdesign-flutter'
      path: 'tdesign-component'
      ref: 'v0.0.2'

**Comment by JackCui001** [comment]
> > > 出现同样的问题，可以给出修复时间吗？不行的话 只能先 fock 自己改了.
> > 
> > 
> > 我暂时先用 flutter downgrade 回退到 3.24.5 了，旧版本一切正常。
> 
> ```
> dependencies
>   tdesign_flutter:
>       git:
>         url: 'https://github.com/bomb-bomb/tdesign-flutter'
>         path: 'tdesign-component'
>         ref: 'v0.0.2'
> 
> dependency_overrides:
>   flutter_slidable:
>     git:
>       url: 'https://github.com/letsar/flutter_slidable'
> ```

今天再看了下，flutter_slidable 那边已经发版修复了，直接指定最新的 3.1.2 就行，这边我也提交了一个PR，不知道啥时候能合并...

**Comment by jackson0122** [comment]
出现同样的问题，可以给出修复时间吗

**Comment by bomb-bomb** [comment]
> > > > 出现同样的问题，可以给出修复时间吗？不行的话 只能先 fock 自己改了.
> > > 
> > > 
> > > 我暂时先用 flutter downgrade 回退到 3.24.5 了，旧版本一切正常。
> > 
> > 
> > ```
> > dependencies
> >   tdesign_flutter:
> >       git:
> >         url: 'https://github.com/bomb-bomb/tdesign-flutter'
> >         path: 'tdesign-component'
> >         ref: 'v0.0.2'
> > 
> > dependency_overrides:
> >   flutter_slidable:
> >     git:
> >       url: 'https://github.com/letsar/flutter_slidable'
> > ```
> 
> 今天再看了下，flutter_slidable 那边已经发版修复了，直接指定最新的 3.1.2 就行，这边我也提交了一个PR，不知道啥时候能合并...
那便如此。先用着。
```
dependencies
  tdesign_flutter:
      git:
        url: 'https://github.com/bomb-bomb/tdesign-flutter'
        path: 'tdesign-component'
        ref: 'v0.0.3'
```

**Comment by usenameI** [comment]
啥时候解决啊，这个tdsign 比flutter sdk的更新速度还慢。。。。。。。。。。
