### ISSUE TITLE
[Swiper] 想要可以没有下面的进度点，单纯的图片，不带任何前进后退提示

### ISSUE THREAD

**Issue by ljfzd6** [Tencent/tdesign-flutter#415]
### 这个功能解决了什么问题

有的时候，单纯需要图片可以翻页展示，不需要提示是第几张和点击前进后退

### 你建议的方案是什么

增加一个参数，可以消除全部的提示按钮和进度点

**Comment by shizhe2018** [comment]
可以不用配置对应属性，就可以实现你的需求
