### ISSUE TITLE
官网企业微信群无法添加

### ISSUE THREAD

**Issue by LiXunGuan** [Tencent/tdesign-flutter#5]
### tdesign-flutter 版本

官网企业微信群无法添加

### 重现步骤

官网企业微信群无法添加

### 期望结果

官网企业微信群无法添加

### 实际结果

官网企业微信群无法添加

### 补充说明

官网企业微信群无法添加

**Comment by Luozf12345** [comment]
由于策略调整，官网二维码的群暂时关闭加入了，后面调整完后会换成新的二维码，现在可以先用这个二维码加入群聊：
![企业微信截图_77d9230c-0b79-40a6-8a23-de36da98ba19](https://github.com/Tencent/tdesign-flutter/assets/35024333/86861b0c-4643-4d1b-b49d-d13b8a0a3ec4)
