### ISSUE TITLE
TDCheckbox自定义size和主题色

### ISSUE THREAD

**Issue by yansyou** [Tencent/tdesign-flutter#57]
### 这个功能解决了什么问题

每个应用的主题色可能不一样，设计尺寸也有区别，希望能自定义传值

### 你建议的方案是什么

希望能自定义传值

**Comment by Luozf12345** [comment]
Icon尺寸可以使用customIconBuilder来进行自定义处理。如果只是改颜色，可以通过修改主题的brandNormalColor来实现，或者通过新增的selectColor和disableColor来修改

**Comment by Luozf12345** [comment]
0.1.4版本已支持
