### ISSUE TITLE
建议搞个Python版本

### ISSUE THREAD

**Issue by monkeycc** [Tencent/tdesign-flutter#6]
Flutter 都能有python版的部署方案
https://github.com/flet-dev/flet

或者做成AI火爆的 gradio 
https://github.com/gradio-app/gradio

我觉得tdesign-flutter也能考虑

**Comment by Luozf12345** [comment]
感谢建议，暂时使用python的用户比较少，先把当前的组件库做好，如果后续有机会的话，会考虑支持。
