### ISSUE TITLE
[按钮组件] 无按压反馈导致看起来很生硬

### ISSUE THREAD

**Issue by sineom-1** [Tencent/tdesign-flutter#7]
### tdesign-flutter 版本

最新版本

**Comment by Luozf12345** [comment]
感谢反馈，请问你指的是Button组件吗？我这边看Button是有点击反馈的，不过点击反馈可能没那边灵敏，长按可以看到，点按的时候不明显，这边后面优化一下。

**Comment by sineom-1** [comment]
是的，长按可以看到。 点击不够灵敏

**Comment by Luozf12345** [comment]
0.1.2版本已修复
