### ISSUE TITLE
TDImage

### ISSUE THREAD

**Issue by thousandsNight** [Tencent/tdesign-flutter#8]
### 这个功能解决了什么问题

瀑布流中放置图片，根据图片宽度自适应高度，请参考flutter官方Image里的fitWidth

### 你建议的方案是什么

请参考flutter官方Image里BoxFit.fitWidth

**Comment by Luozf12345** [comment]
感谢反馈，已收到，这边看下怎么处理

**Comment by Luozf12345** [comment]
0.1.2版本已修复
